import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'zh-CN' | 'zh-TW' | 'ja' | 'ko' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language | 'system') => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    dashboard: 'Dashboard',
    aboutChurch: 'Our Church',
    roster: 'Roster',
    worshipSongs: 'Worship & Songs',
    prayerWall: 'Prayer Wall',
    members: 'Members',
    giving: 'Giving',
    support: 'Support',
    managerPortal: 'MANAGER PORTAL',
    managerMode: 'MANAGER MODE',
    superAdminRole: 'SUPER ADMIN',
    staffMode: 'STAFF MODE',
    memberMode: 'MEMBER MODE',
    newEvent: 'NEW EVENT',
    
    // Login
    welcome: 'Welcome',
    signInDesc: 'Sign in to your community account.',
    applyDesc: 'Apply to become a member.',
    churchCode: 'Church Code',
    fullName: 'Full Name',
    email: 'Email',
    password: 'Password',
    signIn: 'Sign In',
    submitRequest: 'Submit Request',
    moreOptions: 'MORE OPTIONS',
    signUpMember: 'Sign Up to become a member',
    alreadyAccount: 'Already have an account? Sign In',
    managerLogin: 'Manager/Staff Login',
    secureEnv: 'Secure Environment',
    systemLanguage: 'System Language',
    requestSubmitted: 'Request Submitted',
    requestSubmittedDesc: 'Your request to join the community has been sent. A manager or pastor will review your application soon.',
    backToLogin: 'Back to Login',
    // Dashboard
    totalMembers: 'Total Members',
    activeVolunteers: 'Active Volunteers',
    weeklyOffering: 'Weekly Offering',
    newRequests: 'New Requests',
    growth: 'growth',
    fromLastWeek: 'from last week',
    upcomingEvents: 'Upcoming Events',
    prayerRequests: 'Prayer Requests',
    memberApprovals: 'Member Approvals',
    reviewSignUps: 'Review sign-up requests',
    myTasks: 'My Tasks',
    personalToDo: 'Personal to-do list',
    allCaughtUp: 'All caught up!',
    addATask: 'Add a task...',
    addBtn: 'Add',
    approveBtn: 'Approve',
    declineBtn: 'Decline',
    dailyGoldenVerse: 'DAILY GOLDEN VERSE',
    pendingApproval: 'pending approval',
    viewPlan: 'VIEW PLAN',
    servicesDesc: 'Services, weddings, and camps for the month',
    thisMonth: 'this month',
    welcomeBack: 'Welcome back',
    pastorDavid: 'Pastor David',
    teamMember: 'Team Member',
    printRoster: 'Print Roster',
    preparing: 'Preparing...',
    recentActivity: 'Recent Activity',
    loadMore: 'LOAD MORE',
    loading: 'LOADING...',
    justNow: 'Just now',
    minsAgo: 'mins ago',
    hourAgo: '1 hour ago',
    hoursAgo: 'hours ago',
    uploadedPpt: 'uploaded a new ppt for',
    declinedRequest: 'declined scheduling request on',
    submittedPrayer: 'submitted a new prayer request.',
    approvedMembership: 'approved membership for',
    scheduledAction: 'scheduled',
    updatedHistory: 'updated history',
    addedRelationship: 'added relationship',
    followUpVisitors: 'Follow up with new visitors',
    prepareSermonSlides: 'Prepare Sunday sermon slides',
    changeVerse: 'Change Verse',
    editBtn: 'EDIT',
    myService: 'MY SERVICE',
    teamReadiness: 'Team Readiness',
    confirmed: 'confirmed',
    approvals: 'APPROVALS',
    itemsWaiting: 'items waiting',
    newMembers: 'new members',
    searchStaff: 'Search staff...',
    viewAll: 'VIEW ALL',
    teamPreparation: 'Team Preparation',
    pendingItems: 'Pending Items',
    latestSermon: 'Latest Sermon',
    watchOnYoutube: 'WATCH ON YOUTUBE',
    personnel: 'Personnel',
    allStaff: 'All Staff',
    coreValues: 'CORE VALUES',
    love: 'Love',
    serve: 'Serve',
    disciple: 'Disciple',
    navigation: 'NAVIGATE',
    viewMap: 'VIEW MAP',
    founder: 'FOUNDER',
    denomination: 'Denomination',
    highlightEvent: 'HIGHLIGHT EVENT',
    comingNext: 'COMING NEXT',
    upcomingRole: 'Upcoming Role',
    addToCalendar: 'ADD TO CALENDAR',
    liveUpdates: 'LIVE UPDATES',
    eventTitle: 'Event Title',
    type: 'Type',
    date: 'Date',
    reminder: 'Reminder',
    createEvent: 'Create Event',
    sundayWorship: 'Sunday Worship',
    goodFriday: 'Good Friday',
    anniversaryCelebration: 'Anniversary Celebration',
    verse1_quote: 'Faith is the assurance of things hoped for.',
    verse2_quote: 'Grace Abounds',
    verse3_quote: 'Love Never Fails',
    verse4_quote: 'Walk by Faith',
    verse5_quote: 'Peace I Leave with You',
    verse6_quote: 'Be faithful in small things.',
    mainSanctuary: 'Main Sanctuary',
    worshipLeader: 'Worship Leader',
    camping: 'CAMPING',
    days: 'DAYS',
    holyCommunion: 'Holy Communion',
    sundayWorshipService: 'Sunday Worship Service',
    youthWinterCamp: 'Youth Winter Camp',
    johnMaryWedding: 'John & Mary\'s Wedding',
    meeting: 'Meeting',
    search: 'Search...',
    logout: 'Logout',
    howCanIHelp: 'How can I help you today?',
    askAbout: 'Ask about church personnel, service schedules, or theological insights.',
    checkRoster: 'Check Roster',
    memberStats: 'Member Stats',
    prayerList: 'Prayer List',
    askGrace: 'Ask Grace Assistant...',
    outOfTown: '"Out of town this weekend."',
    sunday: 'SUN',
    friday: 'FRI',
    saturday: 'SAT',

    // New additions
    learnMoreAbout: 'LEARN MORE ABOUT OUR VISION, MISSION, AND FAMILY.',
    editDetails: 'EDIT DETAILS',
    churchTitle: 'Grace Community Church',
    churchDesc: 'We are a welcoming community dedicated to sharing love, grace, and hope. Our mission is to serve the city and build a strong family of faith.',
    serviceTimes: 'Service Times',
    serviceTimesDesc: 'Sundays at 9:00 AM & 11:00 AM',
    location: 'Location',
    locationDesc: '123 Grace Ave, Sydney, NSW 2000',
    photoGallery: 'Photo Gallery',

    personalInfo: 'Personal Information',
    editGoldenVerse: 'Edit Golden Verse',
    customWrite: 'Custom Write',
    writeVersePlaceholder: 'Enter the divine wisdom...',
    applyCustom: 'Apply Custom Verse',
    quickSelect: 'Quick Select',
    presets: 'Handpicked Presets',
    firstNameProfile: 'FIRST NAME',
    lastNameProfile: 'LAST NAME',
    emailAddress: 'EMAIL ADDRESS',
    phoneNumber: 'PHONE NUMBER',
    dateOfBirth: 'DATE OF BIRTH',
    age: 'AGE',
    address: 'ADDRESS',
    hometown: 'HOMETOWN / ORIGIN (故鄉)',
    preferredLanguage: 'PREFERRED LANGUAGE',
    joinedLabel: 'Joined',
    statusLabel: 'Status',
    activeStatus: 'Active',
    saveChanges: 'SAVE CHANGES',
    songSourceUrl: 'Song Source URL',
    fetchLyrics: 'FETCH LYRICS',
    fetching: 'FETCHING...',
    invalidUrl: 'Invalid URL. Please enter a valid song link.',
    saveLink: 'Save source link',
    
    serviceRoster: 'Service Roster',
    rosterDesc: 'MANAGE STAFF ASSIGNMENTS AND IDENTIFY SCHEDULING CONFLICTS.',
    monthly: 'MONTHLY',
    weekly: 'WEEKLY',
    availableStaff: 'AVAILABLE STAFF',
    dragToAssign: 'DRAG TO ASSIGN',
    activityLog: 'ACTIVITY LOG',
    assignedToWorship: 'assigned to Worship',
    onLeave: 'On Leave',
    mon: 'MON',
    tue: 'TUE',
    wed: 'WED',
    thu: 'THU',
    
    searchHymns: 'Search Hymns / Praise Songs',
    allSongs: 'ALL',
    worshipSongsTab: 'WORSHIP',
    praiseSongs: 'PRAISE',
    communionSongs: 'COMMUNION',
    defaultKey: 'DEFAULT KEY',
    tempo: 'TEMPO',
    timeSig: 'TIME',
    ccli: 'CCLI',
    lyricsAndChords: 'LYRICS & CHORDS',
    slidesAndMedia: 'SLIDES & MEDIA',
    generatePpt: 'GENERATE PPT FROM LYRICS',
    syncToDrive: 'SYNC TO DRIVE',

    prayerWallDesc: '"DEVOTE YOURSELVES TO PRAYER..." - COLOSSIANS 4:2',
    sharePrayer: 'Share a Prayer',
    whatsOnYourHeart: 'What\'s on your heart?',
    postAnonymously: 'POST ANONYMOUSLY',
    visibility: 'VISIBILITY',
    postPrayer: 'POST PRAYER',
    pray: 'PRAY',
    staffOnly: 'STAFF',
    pendingApprovalTab: 'PENDING',
    allPrayersTab: 'ALL',
    staffInternalTab: 'INTERNAL',
    approve: 'APPROVE',
    reject: 'REJECT',
    keepInternal: 'KEEP INTERNAL',
    originalAuthor: 'ORIGINAL AUTHOR',
    anonymousUser: 'Anonymous',
    confirmedResolved: 'RESOLVED',
    actions: 'ACTIONS',

    // Member Network (Interactive Graph / CRM)
    leads: 'LEADS',
    mentors: 'MENTORS',
    spiritualFamilyLabel: 'SPIRITUAL FAMILY',
    exportNetwork: 'EXPORT GRAPH',
    relationshipChain: 'RELATIONSHIP CHAIN',
    mentorRelationship: 'Mentor',
    familyRelationship: 'Family',
    teamRelationship: 'Team member',
    dragToLinkDesc: 'DRAG ONE NODE TO ANOTHER TO CREATE RELATIONSHIP.',
    exportSuccess: 'Network chain exported successfully.',
    profession: 'INDUSTRY',
    industry: 'INDUSTRY',
    allIndustries: 'All Industries',
    industryEducation: 'Education & Academia',
    industryHealthcare: 'Healthcare & Social Work',
    industryIT: 'IT, Engineering & Tech',
    industryFinance: 'Finance, Law & Professional Services',
    industryBusiness: 'Business, Sales & Retail',
    industryGov: 'Government, Public Policy & Utilities',
    industryArts: 'Arts, Media & Creative',
    industryConstruction: 'Construction, Manufacturing & Skilled Labor',
    industryRetired: 'Retired, Homemakers & Students',
    industryLooking: 'Looking for Opportunities',
    searchMembers: 'Search by name, role or skill...',
    birthday: 'Birthday',
    referralSource: 'Referral Source',
    referralSelf: 'Self-referred',
    referralBy: 'Referred by',
    friendsWith: 'Friends with',
    skillsMinistries: 'Ministries / Skills',
    sundaySchoolTeacher: 'Sunday School Teacher',
    worship: 'Worship',
    leadSinger: 'Lead Singer',
    backingVocal: 'Backing Vocal',
    usher: 'Usher',
    assistantTeacher: 'Assistant Teacher',
    kitchen: 'Kitchen',
    cleaning: 'Cleaning',
    preaching: 'Preaching',
    it: 'IT',
    musician: 'Musician',
    custom: 'New Home Project',

    tasks: 'Tasks',
    allTasks: 'All Tasks',
    editVerse: 'Edit Golden Verse',
    saveVerse: 'Save Verse',

    memberNetwork: 'Member Network',
    memberNetworkDesc: 'VIEW RELATIONSHIPS, SPIRITUAL FAMILIES, AND STAFF DETAILS.',
    listView: 'List View',
    networkView: 'Network View',
    occupationLabel: 'Occupation',
    groupLabel: 'Group',
    allGroups: 'All Groups',
    allOccupations: 'All Occupations',
    crmProfile: 'CRM Profile',
    internalNotes: 'Internal Notes',
    searchName: 'Search name...',
    filterByTag: 'Filter by tag...',
    addMemberBtn: 'ADD',
    interactiveMapping: 'Interactive relationship mapping',
    joinedYear: 'JOINED',
    relationalContext: 'RELATIONAL CONTEXT',
    invitedBy: 'INVITED BY',
    spiritualFamily: 'SPIRITUAL FAMILY',
    personalDetails: 'PERSONAL DETAILS',
    addNewMember: 'Add New Member',
    fullNameStar: 'FULL NAME *',
    tagsRoles: 'TAGS / ROLES',
    spiritualGroup: 'SPIRITUAL FAMILY / GROUP',
    invitedByName: 'INVITED BY (NAME)',
    phoneLabel: 'PHONE NUMBER',
    dobLabel: 'DATE OF BIRTH',
    homeAddress: 'HOME ADDRESS',
    occupation: 'OCCUPATION',
    cancel: 'CANCEL',
    saveMember: 'SAVE MEMBER',
    matchExisting: 'Match an existing member\'s name',
    customTag: 'Custom tag...',

    giveTithes: 'Give Tithes & Offerings',
    giveDesc: '"God loves a cheerful giver." - 2 Cor 9:7',
    customAmount: '$ Custom Amount',
    payApple: 'PAY WITH APPLE PAY',
    payGoogle: 'PAY WITH GOOGLE PAY',
    manualBank: 'OR MANUAL BANK TRANSFER',
    accountName: 'ACCOUNT NAME',
    bsb: 'BSB',
    giveAccountNumber: 'ACCOUNT NUMBER',

    // Financial Dashboard (Manager)
    financeDashboard: 'FINANCIAL MANAGEMENT',
    financeDesc: 'MONITOR CHURCH HEALTH, MANAGE BANK DETAILS AND GATEWAYS.',
    monthlyStats: 'Monthly Offering Overview',
    pendingDonations: 'PENDING TRANSFERS',
    exportReports: 'EXPORT REPORTS',
    configGateways: 'CONFIG GATEWAYS & BANK',
    bsbLabel: 'BSB NUMBER',
    accNoLabel: 'ACCOUNT NUMBER',
    mobilePayments: 'MOBILE PAYMENTS',
    confirmDonation: 'CONFIRM',
    donorName: 'DONOR',
    donationDate: 'DATE',
    donationAmount: 'AMOUNT',
    
    // Placeholders
    egJaneDoe: 'e.g., Jane Doe',
    egYouthGroup: 'e.g., Youth Group',
    egPhone: 'e.g., (555) 123-4567',
    egAddress: 'e.g., 123 Grace Ave, Sydney',
    egOccupation: 'e.g., Software Engineer',
    egHometown: 'e.g., Taipei, Taiwan / Shanghai, China',
    egChurchCode: 'e.g. GRACE-2024',
    egEmail: 'your@email.com',
    egNewTag: 'New tag (e.g. Nursery)',
    ourHistory: 'OUR HISTORY',
    secondaryTime: 'Secondary Time',
    freeParking: 'Free Parking',
    momentsOfGrace: 'Moments of Grace',
    history: 'Our History',
    founders: 'Founders',
    pastors: 'Pastors',
    groupLeaders: 'Group Leaders',
    ourTeam: 'Our Team',
    graceMission: 'To build a home where every soul is restored by grace.',
    foundedYear: 'Founded in 2005',
    independentPentecostal: 'Independent Pentecostal',
    pastorShort: 'Ps.',
    leaderShort: 'Ldr.',
    // Cell Group Schedule
    cellGroupSchedule: 'Weekly Cell Group Schedule',
    cellGroupDesc: 'Meeting locations and times may change. Please contact the group leader for latest updates.',
    meetingName: 'Meeting Name',
    meetingTime: 'Time',
    meetingLocation: 'Location',
    contactPerson: 'Contact',
    note: 'Note',
    morningPrayer: 'Morning Prayer',
    prayerMeeting: 'Prayer Meeting',
    livingStone: 'Living Stone Group',
    rockGroup: 'Rock Group',
    harmoniousGroup: 'Harmonious Group',
    graceGroup: 'Grace Group',
    childrenYouth: 'Children & Youth',

    // Songs & ReadyPPT
    songLibrary: 'Song Library',
    weeklySetlist: 'Weekly Setlist',
    oneClickExport: 'One-Click Export',
    readyPptLib: 'Ready PPT Library',
    firstStepLib: 'Step 1: Prepare Your Library',
    secondStepSetlist: 'Step 2: Arrange Weekly Setlist',
    readyPptStation: 'Ready PPT Workstation',
    finalStepExport: 'Final Step: Resources Ready',
    searchLibrary: 'Search library...',
    addNewSong: 'ADD NEW SONG',
    pptFileName: 'PPT Filename',
    globalLayout: 'Global Layout',
    pairsPerSlide: 'Pairs/Slide',
    totalPageCount: 'Total Pages',
    startGenerate: 'Start Generate PPT',
    generating: 'Generating...',
    exportPptx: 'Export PowerPoint (.pptx)',
    exportPdf: 'Export PDF Report',
    exportRosterPdf: 'Export Roster PDF',
    dragSort: 'Drag to Reorder',
    saveToReadyLib: 'Save to Ready PPT Library',
    previewSetlistDoc: 'Preview Setlist Doc',
    backToLibrary: 'Back to Library',
    backToSetlist: 'Back to Setlist',
    allFiles: 'All Files',
    weeklyWorshipPpt: 'Weekly Worship',
    songSelectionPpt: 'Song Highlights',
    sermonOutline: 'Sermon Outlines',
    searchFiles: 'Search files, titles, or preachers...',
    uploadResource: 'Upload Resource',
    selectCategory: 'Select Category',
    dragDropFiles: 'Drag & Drop Files Here',
    localExportBackup: 'Local Export Backup',
    aiBgGenerated: 'AI Background saved to library',
    generationComplete: 'Generation Complete!',
    resourcesReadyDesc: 'Your worship pack is ready, including lyric slides and handout.',
    lyricOptimization: 'Lyric Optimization',
    perSlide: 'per slide',
    pageCountStr: 'Pages',
    totalCountPages: 'Total {count} Pages',
    preview: 'PREVIEW',
    bgEmerald: 'Deep Forest',
    bgLight: 'Holy Light',
    bgPeace: 'Quiet Moment',
    bgCross: 'Gospel Light',
    bgMountain: 'Mountain Call',
    bgOcean: 'Spirit Water',
    bgStars: 'Starry Sky',
    aiGenerate: 'AI Generate',
    themeInjected: 'Theme Injected',
    readyPptDesc: 'Church resources cloud center. All arranged PPTs, song resources, and sermon outlines are archived here.',
    entryDate: 'Date',
    songIncluded: 'Songs',
    sharePerson: 'Preacher',
    storageLocation: 'Storage',
    onlinePreview: 'Preview',
    downloadFile: 'Download',
    filenameUpdated: 'Filename updated',
    fileRemoved: 'File removed from library',
    successfullyUploaded: 'Successfully uploaded',
    independentBg: 'Ind. Background',
    followTheme: 'Follow Theme',
    pasteLyricsDesc: 'Paste lyrics → Auto-arrange',
    dualLanguageDesc: 'Dual language, saved forever',
    saveDirectlyDesc: 'Directly reuse next time',
    selectFromLibDesc: 'Select songs from library',
    dragToReorderDesc: 'Drag to reorder',
    configBgDesc: 'One-click background config',
    smartMergeDesc: 'Smart merge files',
    pkgPublishDesc: 'Package and publish',
    notifyItDesc: 'Notify IT team in real-time',
    cloudStorageDesc: 'Cloud storage center',
    categorizedDesc: 'By week/song category',
    distPreviewDesc: 'One-click distribution',
    emptySetlistDesc: 'Your setlist is empty, add some songs first',
    searchLibraryPlaceholder: 'Search library...',
    toArrangeSetlist: 'Arrange Weekly Setlist',
    previewSlides: 'Preview Slides',
    uploadSermonOutline: 'Upload weekly sermon outline',
    editSong: 'Edit Song',
    chineseTitle: 'Chinese Title',
    englishTitleLabel: 'English Title / Subtitle',
    chineseLyrics: 'Chinese Lyrics (Original)',
    enterLyricsPlaceholder: 'Enter Chinese lyrics...',
    aiTranslation: 'AI Real-time Translation',
    aiWaitPlaceholder: 'Waiting for AI translation or manual edit...',
    worshipPptDirect: 'Worship PPT Direct',
    cover: 'Cover',
    content: 'Content',
    moreSlidesDesc: 'Next slides will be generated in this format',
    editFileName: 'Edit Filename',
    liveUpdate: 'Live Update',
    enterFileNamePlaceholder: 'Enter PPT filename...',
    themeLibrary: 'Theme Library',
    fileManagement: 'File Management',
    exportSongPpt: 'Export this song PPT',
    editLyrics: 'Edit lyrics',
    summary: 'Summary',
    egAmazingGrace: 'e.g., Amazing Grace',
    egAmazingGraceCn: 'e.g., Amazing Grace',
    translatingViaAi: 'Translating via AI...',
    downloaded: 'Downloaded',
    successfullySaved: 'Successfully Saved',
    generationFailed: 'Generation Failed',
    renderingPreview: 'Rendering preview',
    previewReady: 'Preview ready - check below',
    firstLinePlaceholder: 'First line of lyrics...',
    translatingLine: 'Translation line...',
  },
  'zh-CN': {
    dashboard: '仪表盘',
    aboutChurch: '我们的教会',
    roster: '服事排班',
    worshipSongs: '敬拜诗歌',
    prayerWall: '祷告墙',
    members: '会友',
    giving: '奉献',
    support: '支持',
    managerPortal: '管理员系统',
    managerMode: '管理员模式',
    superAdminRole: '超级管理员',
    staffMode: '同工模式',
    memberMode: '会友模式',
    newEvent: '新建活动',

    welcome: '欢迎',
    signInDesc: '登录您的社区账号。',
    applyDesc: '申请成为会员。',
    churchCode: '教会代码',
    fullName: '姓名',
    email: '邮箱',
    password: '密码',
    signIn: '登录',
    submitRequest: '提交申请',
    moreOptions: '更多选项',
    signUpMember: '注册成为会员',
    alreadyAccount: '已有账号？登录',
    managerLogin: '管理员/同工登录',
    secureEnv: '安全环境',
    systemLanguage: '系统语言',
    requestSubmitted: '申请已提交',
    requestSubmittedDesc: '您的加入申请已发送。管理员或牧师将很快审核您的申请。',
    backToLogin: '返回登录',
    // Dashboard
    totalMembers: '会员总数',
    activeVolunteers: '活跃志愿者',
    weeklyOffering: '本周奉献',
    newRequests: '新请求',
    growth: '增长',
    fromLastWeek: '较上周',
    upcomingEvents: '即将到来的活动',
    prayerRequests: '祷告请求',
    memberApprovals: '会员审批',
    reviewSignUps: '审核注册请求',
    myTasks: '我的任务',
    personalToDo: '个人待办事项',
    allCaughtUp: '全部搞定！',
    addATask: '添加任务...',
    addBtn: '添加',
    approveBtn: '批准',
    declineBtn: '拒绝',
    dailyGoldenVerse: '每日金句',
    pendingApproval: '待审批',
    viewPlan: '查看计划',
    servicesDesc: '本月的礼拜、婚礼和营会',
    thisMonth: '本月',
    welcomeBack: '欢迎回来',
    pastorDavid: '大卫牧师',
    teamMember: '团队成员',
    printRoster: '打印排班表',
    preparing: '正在准备...',
    recentActivity: '近期活动',
    loadMore: '加载更多',
    loading: '加载中...',
    justNow: '刚刚',
    minsAgo: '分钟前',
    hourAgo: '1 小时前',
    hoursAgo: '小时前',
    uploadedPpt: '上传了新的 PPT',
    declinedRequest: '拒绝了排班请求',
    submittedPrayer: '提交了新的祷告请求。',
    approvedMembership: '已批准会员资格',
    scheduledAction: '已安排',
    updatedHistory: '更新了历史',
    addedRelationship: '添加了关系',
    followUpVisitors: '跟进新访客',
    prepareSermonSlides: '准备主日证道幻灯片',
    changeVerse: '更改金句',
    editBtn: '编辑',
    myService: '我的服事',
    teamReadiness: '团队准备情况',
    confirmed: '已确认',
    approvals: '审批',
    itemsWaiting: '项待处理',
    newMembers: '新成员',
    searchStaff: '搜索人员...',
    viewAll: '查看全部',
    teamPreparation: '团队准备情况',
    pendingItems: '待处理事项',
    latestSermon: '最新讲道',
    watchOnYoutube: '在 YouTube 上观看',
    personnel: '人员',
    allStaff: '所有员工',
    coreValues: '核心价值观',
    love: '爱',
    serve: '服事',
    disciple: '门训',
    navigation: '一键导航',
    viewMap: '查看地图',
    founder: '创办人',
    denomination: '宗派',
    highlightEvent: '主要活动',
    comingNext: '接下来',
    upcomingRole: '即将担任的角色',
    addToCalendar: '添加到日历',
    liveUpdates: '实时更新',
    eventTitle: '活动标题',
    type: '类型',
    date: '日期',
    reminder: '提醒',
    createEvent: '创建活动',
    sundayWorship: '主日崇拜',
    goodFriday: '受难日',
    anniversaryCelebration: '周年庆典',
    verse1_quote: '信就是所望之事的实底。',
    verse2_quote: '恩典满溢',
    verse3_quote: '爱是永不止息',
    verse4_quote: '因信而行',
    verse5_quote: '我留下平安给你们',
    verse6_quote: '在小事上忠心。',
    mainSanctuary: '大主殿',
    worshipLeader: '领会',
    camping: '露营',
    days: '天',
    holyCommunion: '圣餐日',
    sundayWorshipService: '主日敬拜礼拜',
    youthWinterCamp: '青年冬令营',
    johnMaryWedding: '约翰和玛丽的婚礼',
    meeting: '会议',
    search: '搜索...',
    logout: '退出',
    howCanIHelp: '今天能怎么帮助您？',
    askAbout: '询问教会同工、服事排班、或神学见解。',
    checkRoster: '查看排班',
    memberStats: '会友统计',
    prayerList: '祷告清单',
    askGrace: '询问 Grace 助理...',
    outOfTown: '"这周末不在城里。"',
    sunday: '周日',
    friday: '周五',
    saturday: '周六',

    // New additions
    learnMoreAbout: '了解有关我们的愿景、使命和家庭的更多信息。',
    editDetails: '编辑详情',
    churchTitle: '恩典社区教会',
    churchDesc: '我们是一个受欢迎的社区，致力于分享爱、恩典和希望。我们的使命是服务城市并建立强大的信仰家庭。',
    serviceTimes: '礼拜时间',
    serviceTimesDesc: '周日上午 9:00 和 11:00',
    location: '位置',
    locationDesc: '123 Grace Ave, Sydney, NSW 2000',
    photoGallery: '照片库',
    personalInfo: '个人信息',
    editGoldenVerse: '编辑每日金句',
    customWrite: '自定义编写',
    writeVersePlaceholder: '输入你的感悟或经文...',
    applyCustom: '应用自定义金句',
    quickSelect: '快速选择',
    presets: '精选预设',
    firstNameProfile: '名字',
    lastNameProfile: '姓氏',
    emailAddress: '电子邮件地址',
    phoneNumber: '电话号码',
    dateOfBirth: '出生日期',
    age: '年龄',
    address: '地址',
    hometown: '家乡/起源',
    preferredLanguage: '首选语言',
    joinedLabel: '已加入',
    statusLabel: '状态',
    activeStatus: '活动',
    saveChanges: '保存更改',
    songSourceUrl: '诗歌链接 (URL)',
    fetchLyrics: '提取歌词',
    fetching: '正在提取...',
    invalidUrl: '链接无效，请输入有效的诗歌链接。',
    saveLink: '保存原链接',
    serviceRoster: '服务排班',
    rosterDesc: '管理员工分配和识别日程冲突。',
    monthly: '每月',
    weekly: '每周',
    availableStaff: '可用员工',
    dragToAssign: '拖拽以分配',
    activityLog: '活动日志',
    assignedToWorship: '被分配到敬拜',
    onLeave: '休假中',
    mon: '周一',
    tue: '周二',
    wed: '周三',
    thu: '周四',
    searchHymns: '搜索赞美诗/敬拜诗歌',
    allSongs: '全部',
    worshipSongsTab: '敬拜',
    praiseSongs: '赞美',
    communionSongs: '圣餐',
    defaultKey: '默认音调',
    tempo: '节奏',
    timeSig: '节拍',
    ccli: 'CCLI',
    lyricsAndChords: '歌词和和弦',
    slidesAndMedia: '幻灯片和媒体',
    generatePpt: '从歌词生成PPT',
    syncToDrive: '同步到云盘',
    prayerWallDesc: '“你们要恒切祷告…” - 歌罗西书 4:2',
    sharePrayer: '分享您的祷告',
    whatsOnYourHeart: '您心里在想什么？',
    postAnonymously: '匿名发布',
    visibility: '可见性',
    postPrayer: '发布祷告',
    pray: '祷告',
    staffOnly: '同工',
    pendingApprovalTab: '待审核',
    allPrayersTab: '全部',
    staffInternalTab: '内部',
    approve: '批准',
    reject: '驳回',
    keepInternal: '设为内部',
    originalAuthor: '原始发布者',
    anonymousUser: '匿名用户',
    confirmedResolved: '已解决',
    actions: '操作',

    // Member Network
    leads: '带领',
    mentors: '辅助',
    spiritualFamilyLabel: '属灵家庭',
    exportNetwork: '导出图谱',
    relationshipChain: '关系链',
    mentorRelationship: '导师',
    familyRelationship: '家属',
    teamRelationship: '同工',
    dragToLinkDesc: '拖拽一个节点到另一个节点上以建立关系。',
    exportSuccess: '关系链导出成功。',
    profession: '行业',
    industry: '行业',
    allIndustries: '所有行业',
    industryEducation: '教育与学术',
    industryHealthcare: '医疗卫生与社会福利',
    industryIT: '科技、工程与资讯',
    industryFinance: '金融、法律与专业服务',
    industryBusiness: '商业营销、贸易与零售',
    industryGov: '公务、司法与公共事业',
    industryArts: '艺术、传媒与创意产业',
    industryConstruction: '营造、制造与技术劳务',
    industryRetired: '退休、家管与学生',
    industryLooking: '求职中 (Looking for Opportunities)',
    searchMembers: '搜索姓名、角色或技能...',
    birthday: '生日',
    referralSource: '经由哪位介绍？',
    referralSelf: '自己来',
    referralBy: '由谁介绍',
    friendsWith: '朋友关系',
    skillsMinistries: '服事项目 / 技能',
    sundaySchoolTeacher: '主日学老师',
    worship: '敬拜',
    leadSinger: '主唱',
    backingVocal: '帮唱',
    usher: '招待',
    assistantTeacher: '助教',
    kitchen: '厨房',
    cleaning: '清洁',
    preaching: '讲道',
    it: 'IT',
    musician: '乐手',
    custom: '新家项目',
    addMember: '添加新会友',

    tasks: '任务',
    allTasks: '所有任务',
    editVerse: '更改金句',
    saveVerse: '保存金句',
    memberNetwork: '会友网络',
    memberNetworkDesc: '查看关系、属灵家庭和同工详情。',
    listView: '列表视图',
    networkView: '关系视图',
    occupationLabel: '职业',
    groupLabel: '小组',
    allGroups: '所有小组',
    allOccupations: '所有职业',
    crmProfile: 'CRM 档案',
    internalNotes: '内部备注',
    searchName: '搜索姓名...',
    filterByTag: '按标签过滤...',
    addMemberBtn: '添加',
    interactiveMapping: '互动关系图',
    joinedYear: '已加入',
    relationalContext: '关系上下文',
    invitedBy: '邀请人',
    spiritualFamily: '属灵家庭',
    personalDetails: '个人详情',
    addNewMember: '添加新会友',
    fullNameStar: '全名 *',
    tagsRoles: '标签 / 角色',
    spiritualGroup: '属灵家庭 / 小组',
    invitedByName: '邀请人 (姓名)',
    phoneLabel: '电话号码',
    dobLabel: '出生日期',
    homeAddress: '家庭住址',
    occupation: '职业',
    cancel: '取消',
    saveMember: '保存会友',
    matchExisting: '匹配现有会友姓名',
    customTag: '自定义标签...',
    giveTithes: '十一奉献',
    giveDesc: '“捐得乐意的人是神所喜爱的。” - 林后 9:7',
    customAmount: '$ 自定义金额',
    payApple: '使用APPLE PAY支付',
    payGoogle: '使用GOOGLE PAY支付',
    manualBank: '或手动银行转账',
    accountName: '账户名',
    bsb: 'BSB',
    giveAccountNumber: '账号',

    // Financial Dashboard (Manager)
    financeDashboard: '财务管理后台',
    financeDesc: '监控教会财务健康状况，管理银行详情及支付网关。',
    monthlyStats: '本月奉献概览',
    pendingDonations: '待确认转账',
    exportReports: '导出报表',
    configGateways: '配置网关与银行',
    bsbLabel: 'BSB 编号',
    accNoLabel: '账号',
    mobilePayments: '移动支付',
    confirmDonation: '确认',
    donorName: '捐赠者',
    donationDate: '日期',
    donationAmount: '金额',

    egJaneDoe: '例如：张三',
    egYouthGroup: '例如：青年团契',
    egPhone: '例如：(555) 123-4567',
    egAddress: '例如：上海市浦东新区',
    egOccupation: '例如：软件工程师',
    egHometown: '例如：台湾台北, 中国上海',
    egChurchCode: '例如：GRACE-2024',
    egEmail: 'your@email.com',
    egNewTag: '新标签（例如：托儿所）',
    ourHistory: '我们的历史',
    secondaryTime: '祷告会',
    freeParking: '提供免费泊车',
    momentsOfGrace: '感恩瞬间',
    history: '教会历史',
    founders: '创办人',
    pastors: '牧师',
    groupLeaders: '小组长',
    ourTeam: '我们的团队',
    graceMission: '致力于建立一个每个灵魂都能被恩典更新的家园。',
    foundedYear: '成立于 2005 年',
    independentPentecostal: '独立五旬节派',
    pastorShort: '牧',
    leaderShort: '长',
    // Cell Group Schedule
    cellGroupSchedule: '周间小组聚会时间表',
    cellGroupDesc: '时间地点可能随时变动，请联系小组联络人来获得最新资讯。',
    meetingName: '聚会名称',
    meetingTime: '聚会时间',
    meetingLocation: '聚会地点',
    contactPerson: '联络人',
    note: '备注',
    morningPrayer: '晨祷',
    prayerMeeting: '祷告会',
    livingStone: '活石小组',
    rockGroup: '磐石小组',
    harmoniousGroup: '合意小组',
    graceGroup: '恩典小组',
    childrenYouth: '儿少小组',

    // Songs & ReadyPPT
    songLibrary: '核心歌库',
    weeklySetlist: '本周敬拜清单',
    oneClickExport: '一键导出 PPT',
    readyPptLib: 'Ready PPT 库',
    firstStepLib: '第一步：准备好你的核心歌库',
    secondStepSetlist: '第二步：编排本周敬拜清单',
    readyPptStation: 'Ready PPT 工作站',
    finalStepExport: '最后一步：文件已就绪',
    searchLibrary: '快速搜索歌库...',
    addNewSong: '录入新歌',
    pptFileName: 'PPT 文件名',
    globalLayout: '全局排版',
    pairsPerSlide: '对/页',
    totalPageCount: '个页面',
    startGenerate: '开始生成 PPT',
    generating: '拼命生成中...',
    exportPptx: '导出 PowerPoint (.pptx)',
    exportPdf: '导出 PDF 报告',
    exportRosterPdf: '导出排班表 PDF',
    dragSort: '拖拽排序',
    saveToReadyLib: '存入 Ready PPT 数据库',
    previewSetlistDoc: '预览歌单文本',
    backToLibrary: '返回歌库添加歌曲',
    backToSetlist: '返回并修改本周清单',
    allFiles: '全部文件',
    weeklyWorshipPpt: '本周敬拜 PPT',
    songSelectionPpt: '单曲歌库 PPT',
    sermonOutline: '讲道 PPT',
    searchFiles: '搜索文件、歌名或讲员...',
    uploadResource: '上传资源',
    selectCategory: '选择资源分类',
    dragDropFiles: '拖拽文件到此处',
    localExportBackup: '本地导出备份',
    aiBgGenerated: 'AI 背景已自动保存至库',
    generationComplete: '制作完成！',
    resourcesReadyDesc: '您的敬拜资源包已准备就绪，包含歌词幻灯片及本周歌单手册。',
    lyricOptimization: '歌词优化排版',
    perSlide: '每页',
    pageCountStr: '页',
    totalCountPages: '合计 {count} 页',
    preview: '预览',
    bgEmerald: '森林深绿',
    bgLight: '圣洁光芒',
    bgPeace: '宁静时刻',
    bgCross: '福音之光',
    bgMountain: '群山呼唤',
    bgOcean: '圣灵如水',
    bgStars: '星空穹苍',
    aiGenerate: 'AI 生成',
    themeInjected: '已注入主题',
    readyPptDesc: '这里是教会的敬拜资源云端中心。所有已编排的 PPT、单曲资源和讲道大纲都会在此自动存档。',
    entryDate: '录入日期',
    songIncluded: '歌曲包含',
    sharePerson: '分享人',
    storageLocation: '存储位置',
    onlinePreview: '在线预览',
    downloadFile: '下载文件',
    filenameUpdated: '文件名已更新',
    fileRemoved: '文件已从库中移除',
    successfullyUploaded: '成功上传了一个资源',
    independentBg: '独立背景图',
    followTheme: '随全局主题',
    pasteLyricsDesc: '贴入歌词 → 自动整理',
    dualLanguageDesc: '中英对照，永久保存',
    saveDirectlyDesc: '下次敬拜直接调用',
    selectFromLibDesc: '从歌库选歌入列',
    dragToReorderDesc: '自由拖拽排序',
    configBgDesc: '一键配置背景图',
    smartMergeDesc: '智能合并文件',
    pkgPublishDesc: '文件打包发布',
    notifyItDesc: '实时通知 IT 同工',
    cloudStorageDesc: '云端存储中心',
    categorizedDesc: '按周/歌曲分类',
    distPreviewDesc: '一键分发与预览',
    emptySetlistDesc: '你的清单还是空的，请先从歌库添加歌曲',
    searchLibraryPlaceholder: '快速搜索歌库...',
    toArrangeSetlist: '去编排本周敬拜清单',
    previewSlides: '预览幻灯片',
    uploadSermonOutline: '上传本周讲道大纲',
    editSong: '编辑歌曲',
    chineseTitle: '中文歌名',
    englishTitleLabel: '英文歌名 / 副标题',
    chineseLyrics: '中文歌词 (Original)',
    enterLyricsPlaceholder: '输入中文歌词...',
    aiTranslation: 'AI 实时翻译 (Translation)',
    aiWaitPlaceholder: '等待 AI 翻译或手动编辑...',
    worshipPptDirect: 'Worship PPT 直连',
    cover: '封面',
    content: '正文',
    moreSlidesDesc: '后续幻灯片将按此格式生成',
    editFileName: '修改文件名',
    liveUpdate: '实时更新',
    enterFileNamePlaceholder: '输入 PPT 文件名称...',
    themeLibrary: '主题背景库',
    fileManagement: '文件管理',
    exportSongPpt: '导出此歌曲 PPT',
    editLyrics: '修改此歌词',
    summary: '歌单概要',
    egAmazingGraceCn: '例如：奇异恩典',
    egAmazingGrace: '例如：Amazing Grace',
    translatingViaAi: 'AI 翻译中...',
    downloaded: '已下载',
    successfullySaved: '已成功保存',
    generationFailed: '生成失败',
    renderingPreview: '正在渲染预览',
    previewReady: '预览已就绪 - 就在下方查看',
    firstLinePlaceholder: '歌词第一行...',
    translatingLine: '翻译行...',
  },
  'zh-TW': {
    dashboard: '儀表板',
    aboutChurch: '我們的教會',
    roster: '服事排班',
    worshipSongs: '敬拜詩歌',
    prayerWall: '禱告牆',
    members: '會友',
    giving: '奉獻',
    support: '支持',
    managerPortal: '管理員系統',
    managerMode: '管理員模式',
    staffMode: '同工模式',
    memberMode: '會友模式',
    newEvent: '新建活動',

    welcome: '歡迎',
    signInDesc: '登入您的社區帳號。',
    applyDesc: '申請成為會員。',
    churchCode: '教會代碼',
    fullName: '姓名',
    email: '郵箱',
    password: '密碼',
    signIn: '登入',
    submitRequest: '提交申請',
    moreOptions: '更多選項',
    signUpMember: '註冊成為會員',
    alreadyAccount: '已有帳號？登入',
    managerLogin: '管理員/同工登入',
    secureEnv: '安全環境',
    systemLanguage: '系統語言',
    requestSubmitted: '申請已提交',
    requestSubmittedDesc: '您的加入申請已發送。管理員或牧師將很快審核您的申請。',
    backToLogin: '返回登入',
    // Dashboard
    totalMembers: '會友總數',
    activeVolunteers: '活躍志工',
    weeklyOffering: '本週奉獻',
    newRequests: '新請求',
    growth: '增長',
    fromLastWeek: '較上週',
    upcomingEvents: '即將到來的活動',
    prayerRequests: '禱告請求',
    memberApprovals: '會員審批',
    reviewSignUps: '審核註冊請求',
    myTasks: '我的任務',
    personalToDo: '個人待辦事項',
    allCaughtUp: '全部搞定！',
    addATask: '添加任務...',
    addBtn: '添加',
    approveBtn: '批准',
    declineBtn: '拒絕',
    dailyGoldenVerse: '每日金句',
    pendingApproval: '待審批',
    viewPlan: '查看計畫',
    servicesDesc: '本月的禮拜、婚禮和營會',
    thisMonth: '本月',
    welcomeBack: '歡迎回來',
    pastorDavid: '大衛牧師',
    teamMember: '團隊成員',
    printRoster: '列印排班表',
    preparing: '準備中...',
    recentActivity: '近期活動',
    loadMore: '載入更多',
    loading: '載入中...',
    justNow: '剛剛',
    minsAgo: '分鐘前',
    hourAgo: '1 小時前',
    hoursAgo: '小時前',
    uploadedPpt: '上傳了新的 PPT',
    declinedRequest: '拒絕了排班請求',
    submittedPrayer: '提交了新的禱告請求。',
    approvedMembership: '已批准會員資格',
    scheduledAction: '已安排',
    updatedHistory: '更新了歷史',
    addedRelationship: '添加了關係',
    followUpVisitors: '跟進新訪客',
    prepareSermonSlides: '準備主日證道投影片',
    changeVerse: '更改金句',
    editBtn: '編輯',
    myService: '我的服事',
    teamReadiness: '團隊準備情況',
    confirmed: '已確認',
    approvals: '審批',
    itemsWaiting: '項待處理',
    newMembers: '新成員',
    searchStaff: '搜尋人員...',
    viewAll: '查看全部',
    teamPreparation: '團隊準備情況',
    pendingItems: '待處理事項',
    latestSermon: '最新講道',
    watchOnYoutube: '在 YouTube 上觀看',
    personnel: '人員',
    allStaff: '所有員工',
    coreValues: '核心價值觀',
    love: '愛',
    serve: '服事',
    disciple: '門訓',
    navigation: '一鍵導航',
    viewMap: '查看地圖',
    founder: '創辦人',
    denomination: '宗派',
    highlightEvent: '主要活動',
    comingNext: '接下來',
    upcomingRole: '即將擔任的角色',
    addToCalendar: '添加到日曆',
    liveUpdates: '實時更新',
    eventTitle: '活動標題',
    type: '類型',
    date: '日期',
    reminder: '提醒',
    createEvent: '創建活動',
    sundayWorship: '主日崇拜',
    goodFriday: '受難日',
    anniversaryCelebration: '週年慶典',
    verse1_quote: '信就是所望之事的實底。',
    verse2_quote: '恩典滿溢',
    verse3_quote: '愛是永不止息',
    verse4_quote: '因信而行',
    verse5_quote: '我留下平安給你們',
    verse6_quote: '在小事上忠心。',
    mainSanctuary: '大主殿',
    worshipLeader: '領會',
    camping: '露營',
    days: '天',
    holyCommunion: '聖餐日',
    sundayWorshipService: '主日敬拜禮拜',
    youthWinterCamp: '青年冬令營',
    johnMaryWedding: '約翰和瑪麗的婚禮',
    meeting: '會議',
    search: '搜尋...',
    logout: '登出',
    howCanIHelp: '今天能怎麼幫助您？',
    askAbout: '詢問教會同工、服事排班、或神學見解。',
    checkRoster: '查看排班',
    memberStats: '會友統計',
    prayerList: '禱告清單',
    askGrace: '詢問 Grace 助理...',
    outOfTown: '"這週末不在城裡。"',
    sunday: '週日',
    friday: '週五',
    saturday: '週六',

    // New additions
    learnMoreAbout: '了解有關我們的願景、使命和家庭的更多資訊。',
    editDetails: '編輯詳情',
    churchTitle: '恩典社區教會',
    churchDesc: '我們是一個受歡迎的社區，致力於分享愛、恩典和希望。我們的使命是服務城市並建立強大的信仰家庭。',
    serviceTimes: '禮拜時間',
    serviceTimesDesc: '週日上午 9:00 和 11:00',
    location: '位置',
    locationDesc: '123 Grace Ave, Sydney, NSW 2000',
    photoGallery: '照片庫',
    personalInfo: '個人信息',
    firstNameProfile: '名字',
    lastNameProfile: '姓氏',
    emailAddress: '電子郵件地址',
    phoneNumber: '電話號碼',
    dateOfBirth: '出生日期',
    age: '年齡',
    address: '地址',
    hometown: '家鄉/起源',
    preferredLanguage: '首選語言',
    joinedLabel: '已加入',
    statusLabel: '狀態',
    activeStatus: '活動',
    saveChanges: '保存更改',
    serviceRoster: '服務排班',
    rosterDesc: '管理員工分配和識別日程衝突。',
    monthly: '每月',
    weekly: '每週',
    availableStaff: '可用員工',
    dragToAssign: '拖曳以分配',
    activityLog: '活動日誌',
    assignedToWorship: '被分配到敬拜',
    onLeave: '休假中',
    mon: '週一',
    tue: '週二',
    wed: '週三',
    thu: '週四',
    searchHymns: '搜尋讚美詩/敬拜詩歌',
    allSongs: '全部',
    worshipSongsTab: '敬拜',
    praiseSongs: '讚美',
    communionSongs: '聖餐',
    defaultKey: '預設音調',
    tempo: '節奏',
    timeSig: '節拍',
    ccli: 'CCLI',
    lyricsAndChords: '歌詞和和弦',
    slidesAndMedia: '幻燈片和媒體',
    generatePpt: '從歌詞生成PPT',
    syncToDrive: '同步到雲端',
    prayerWallDesc: '“你們要恆切禱告…” - 歌羅西書 4:2',
    sharePrayer: '分享您的禱告',
    whatsOnYourHeart: '您心裡在想什麼？',
    postAnonymously: '匿名發布',
    visibility: '可見性',
    postPrayer: '發布禱告',
    pray: '禱告',
    staffOnly: '同工',
    pendingApprovalTab: '待審核',
    allPrayersTab: '全部',
    staffInternalTab: '內部',
    approve: '批准',
    reject: '駁回',
    keepInternal: '設為內部',
    originalAuthor: '原始發布者',
    anonymousUser: '匿名用戶',
    confirmedResolved: '已解決',
    actions: '操作',

    // Member Network
    leads: '帶領',
    mentors: '輔助',
    spiritualFamilyLabel: '屬靈家庭',
    exportNetwork: '導出圖譜',
    relationshipChain: '關係鏈',
    mentorRelationship: '導師',
    familyRelationship: '家屬',
    teamRelationship: '同工',
    dragToLinkDesc: '拖拽一個節點到另一個節點上以建立關係。',
    exportSuccess: '關係鏈導出成功。',
    profession: '行業',
    industry: '行業',
    allIndustries: '所有行業',
    industryEducation: '教育與學術',
    industryHealthcare: '醫療衛生與社會福利',
    industryIT: '科技、工程與資訊',
    industryFinance: '金融、法律與專業服務',
    industryBusiness: '商業營銷、貿易與零售',
    industryGov: '公務、司法與公共事業',
    industryArts: '藝術、傳媒與創意產業',
    industryConstruction: '營造、製造與技術勞務',
    industryRetired: '退休、家管與學生',
    industryLooking: '求職中 (Looking for Opportunities)',
    searchMembers: '搜尋姓名、角色或技能...',
    birthday: '生日',
    referralSource: '經由哪位介紹？',
    referralSelf: '自己來',
    referralBy: '由誰介紹',
    friendsWith: '朋友關係',
    skillsMinistries: '服事項目 / 技能',
    sundaySchoolTeacher: '主日學老師',
    worship: '敬拜',
    leadSinger: '主唱',
    backingVocal: '幫唱',
    usher: '招待',
    assistantTeacher: '助教',
    kitchen: '廚房',
    cleaning: '清潔',
    preaching: '講道',
    it: 'IT',
    musician: '樂手',
    custom: '新家項目',
    addMember: '添加新會友',

    tasks: '任務',
    allTasks: '所有任務',
    editVerse: '更改金句',
    saveVerse: '保存金句',
    memberNetwork: '會友網絡',
    memberNetworkDesc: '查看關係、屬靈家庭和同工詳情。',
    listView: '列表視圖',
    networkView: '關係視圖',
    occupationLabel: '職業',
    groupLabel: '小組',
    allGroups: '所有小組',
    allOccupations: '所有職業',
    crmProfile: 'CRM 檔案',
    internalNotes: '內部備註',
    searchName: '搜尋姓名...',
    filterByTag: '按標籤過濾...',
    addMemberBtn: '新增',
    interactiveMapping: '互動關係圖',
    joinedYear: '已加入',
    relationalContext: '關係上下文',
    invitedBy: '邀請人',
    spiritualFamily: '屬靈家庭',
    personalDetails: '個人詳情',
    addNewMember: '新增新會友',
    fullNameStar: '全名 *',
    tagsRoles: '標籤 / 角色',
    spiritualGroup: '屬靈家庭 / 小組',
    invitedByName: '邀請人 (姓名)',
    phoneLabel: '電話號碼',
    dobLabel: '出生日期',
    homeAddress: '家庭住址',
    occupation: '職業',
    cancel: '取消',
    saveMember: '保存會友',
    matchExisting: '匹配現有會友姓名',
    customTag: '自定義標籤...',
    giveTithes: '十一奉獻',
    giveDesc: '“捐得樂意的人是神所喜愛的。” - 林後 9:7',
    customAmount: '$ 自定義金額',
    payApple: '使用APPLE PAY支付',
    payGoogle: '使用GOOGLE PAY支付',
    manualBank: '或手動銀行轉帳',
    accountName: '帳戶名稱',
    bsb: 'BSB',
    giveAccountNumber: '帳號',

    // Financial Dashboard (Manager)
    financeDashboard: '財務管理後台',
    financeDesc: '監控教會財務健康狀況，管理銀行詳情及支付網關。',
    monthlyStats: '本月奉獻概覽',
    pendingDonations: '待確認轉賬',
    exportReports: '導出報表',
    configGateways: '配置網關與銀行',
    bsbLabel: 'BSB 編號',
    accNoLabel: '帳號',
    mobilePayments: '移動支付',
    confirmDonation: '確認',
    donorName: '捐贈者',
    donationDate: '日期',
    donationAmount: '金額',

    egJaneDoe: '例如：王小明',
    egYouthGroup: '例如：青年團契',
    egPhone: '例如：(555) 123-4567',
    egAddress: '例如：台北市信義區',
    egOccupation: '例如：軟體工程師',
    egHometown: '例如：台灣台北, 中國上海',
    egChurchCode: '例如：GRACE-2024',
    egEmail: 'your@email.com',
    egNewTag: '新標籤（例如：托兒所）',
    history: '教會歷史',
    founders: '創辦人',
    pastors: '牧師',
    groupLeaders: '小組長',
    ourTeam: '我們的團隊',
    graceMission: '致力於建立一個每個靈魂都能被恩典更新的家園。',
    foundedYear: '成立於 2005 年',
    independentPentecostal: '獨立五旬節派',
    pastorShort: '牧',
    leaderShort: '長',
    // Cell Group Schedule
    cellGroupSchedule: '週間小組聚會時間表',
    cellGroupDesc: '時間地點可能隨時變動，請聯繫小組聯絡人來獲得最新資訊。',
    meetingName: '聚會名稱',
    meetingTime: '聚會時間',
    meetingLocation: '聚會地點',
    contactPerson: '聯絡人',
    note: '備註',
    morningPrayer: '晨禱',
    prayerMeeting: '禱告會',
    livingStone: '活石小組',
    rockGroup: '磐石小組',
    harmoniousGroup: '合意小組',
    graceGroup: '恩典小組',
    childrenYouth: '兒少小組',
  },
  'ja': {
    dashboard: 'ダッシュボード',
    aboutChurch: '教会について',
    roster: '名簿',
    worshipSongs: '賛美歌と歌',
    prayerWall: '祈りの壁',
    members: 'メンバー',
    giving: '寄付',
    support: 'サポート',
    managerPortal: 'マネージャーポータル',
    managerMode: 'マネージャーモード',
    staffMode: 'スタッフモード',
    memberMode: 'メンバーモード',
    newEvent: '新規イベント',

    welcome: 'ようこそ',
    signInDesc: 'コミュニティアカウントにサインインします。',
    applyDesc: 'メンバーになるために申し込む。',
    churchCode: '教会コード',
    fullName: '氏名',
    email: 'メールアドレス',
    password: 'パスワード',
    signIn: 'サインイン',
    submitRequest: 'リクエストを送信',
    moreOptions: 'その他のオプション',
    signUpMember: 'サインアップしてメンバーになる',
    alreadyAccount: 'すでにアカウントをお持ちですか？サインイン',
    managerLogin: 'マネージャー/スタッフログイン',
    secureEnv: '安全な環境',
    systemLanguage: 'システム言語',
    requestSubmitted: 'リクエスト送信済み',
    requestSubmittedDesc: '参加リクエストが送信されました。マネージャーまたは牧師がまもなく申請を審査します。',
    backToLogin: 'ログインに戻る',
    // Dashboard
    totalMembers: 'メンバー総数',
    activeVolunteers: 'アクティブなボランティア',
    weeklyOffering: '今週の献金',
    newRequests: '新しいリクエスト',
    growth: '増加',
    fromLastWeek: '先週から',
    upcomingEvents: '今後の予定',
    prayerRequests: '祈りのリクエスト',
    memberApprovals: 'メンバー承認',
    reviewSignUps: 'サインアップリクエストを確認',
    myTasks: '私のタスク',
    personalToDo: 'パーソナルToDoリスト',
    allCaughtUp: 'すべて完了！',
    addATask: 'タスクを追加...',
    addBtn: '追加',
    approveBtn: '承認',
    declineBtn: '拒否',
    dailyGoldenVerse: '今日の聖句',
    pendingApproval: '承認待ち',
    viewPlan: 'プランを見る',
    servicesDesc: '今月の礼拝、結婚式、キャンプ',
    thisMonth: '今月',
    welcomeBack: 'お帰りなさい',
    pastorDavid: 'デビッド牧師',
    teamMember: 'チームメンバー',
    printRoster: '名簿を印刷',
    preparing: '準備中...',
    recentActivity: '最近の活動',
    loadMore: 'もっと読み込む',
    loading: '読み込み中...',
    justNow: 'たった今',
    minsAgo: '分前',
    hourAgo: '1 時間前',
    hoursAgo: '時間前',
    uploadedPpt: '新しいPPTをアップロード',
    declinedRequest: 'スケジュールのリクエストを辞退',
    submittedPrayer: '新しい祈りのリクエストを送信',
    camping: 'キャンプ',
    days: '日',
    holyCommunion: '聖餐式',
    sundayWorshipService: '日曜礼拝',
    youthWinterCamp: 'ユースウィンターキャンプ',
    johnMaryWedding: 'ジョンとメアリーの結婚式',
    search: '検索...',
    logout: 'ログアウト',
    howCanIHelp: '今日はどのようにお手伝いしましょうか？',
    askAbout: '教会のスタッフ、奉仕のスケジュール、または神学的な洞察について尋ねてください。',
    checkRoster: '予定表を確認',
    memberStats: 'メンバー統計',
    prayerList: '祈りのリスト',
    askGrace: 'Graceアシスタントに尋ねる...',
    outOfTown: '"今週末は市外にいます。"',
    sunday: '日',
    friday: '金',
    saturday: '土',

    // New additions
    learnMoreAbout: 'ビジョン、ミッション、そして家族について詳しくはこちら。',
    editDetails: '詳細を編集',
    churchTitle: 'グレースコミュニティ教会',
    churchDesc: '私たちは愛、恵み、希望を分かち合うことに献身する歓迎するコミュニティです。私たちの使命は、都市に奉仕し、強固な信仰の家族を築くことです。',
    serviceTimes: '礼拝時間',
    serviceTimesDesc: '日曜日 午前9:00と午前11:00',
    location: '場所',
    locationDesc: '123 Grace Ave, Sydney, NSW 2000',
    photoGallery: 'フォトギャラリー',
    personalInfo: '個人情報',
    firstNameProfile: '名',
    lastNameProfile: '姓',
    emailAddress: 'メールアドレス',
    phoneNumber: '電話番号',
    dateOfBirth: '生年月日',
    age: '年齢',
    address: '住所',
    hometown: '出身地',
    preferredLanguage: '使用言語',
    joinedLabel: '参加済み',
    statusLabel: 'ステータス',
    activeStatus: 'アクティブ',
    saveChanges: '変更を保存',
    serviceRoster: 'サービス名簿',
    rosterDesc: 'スタッフの割り当てを管理し、スケジュールの競合を特定します。',
    monthly: '毎月',
    weekly: '毎週',
    availableStaff: '対応可能なスタッフ',
    dragToAssign: 'ドラッグして割り当てる',
    activityLog: '活動ログ',
    assignedToWorship: '礼拝に割り当てられました',
    onLeave: '休暇中',
    mon: '月',
    tue: '火',
    wed: '水',
    thu: '木',
    searchHymns: '賛美歌/歌を検索',
    allSongs: 'すべて',
    worshipSongsTab: '礼拝',
    praiseSongs: '賛美',
    communionSongs: '聖餐式',
    defaultKey: 'デフォルトキー',
    tempo: 'テンポ',
    timeSig: '拍子',
    ccli: 'CCLI',
    lyricsAndChords: '歌詞とコード',
    slidesAndMedia: 'スライドとメディア',
    generatePpt: '歌詞からPPTを生成',
    syncToDrive: 'ドライブに同期',
    prayerWallDesc: '「祈りに専念しなさい…」 - コロサイ 4:2',
    sharePrayer: '祈りを共有する',
    whatsOnYourHeart: 'あなたの心にあることは何ですか？',
    postAnonymously: '匿名で投稿',
    visibility: '公開範囲',
    postPrayer: '祈りを投稿',
    pray: '祈る',
    staffOnly: 'スタッフ',
    memberNetwork: 'メンバーネットワーク',
    memberNetworkDesc: '関係、スピリチュアルな家族、スタッフの詳細を表示。',
    searchName: '名前で検索...',
    filterByTag: 'タグで絞り込み...',
    addMemberBtn: '追加',
    interactiveMapping: 'インタラクティブな関係マッピング',
    joinedYear: '参加年',
    relationalContext: '関係のコンテキスト',
    invitedBy: '招待者',
    spiritualFamily: 'スピリチュアルファミリー',
    personalDetails: '個人情報',
    addNewMember: '新規メンバーを追加',
    fullNameStar: 'フルネーム *',
    tagsRoles: 'タグ / 役割',
    spiritualGroup: 'スピリチュアルファミリー/グループ',
    invitedByName: '招待者（氏名）',
    phoneLabel: '電話番号',
    dobLabel: '生年月日',
    homeAddress: '自宅住所',
    occupation: '職業',
    cancel: 'キャンセル',
    saveMember: 'メンバーを保存',
    matchExisting: '既存メンバーの名前と一致',
    customTag: 'カスタムタグ...',
    giveTithes: '十分の一献金と捧げ物',
    giveDesc: '「神は喜んで与える人を愛してくださる。」 - 第2コリント9:7',
    customAmount: '$ カスタム額',
    payApple: 'APPLE PAYで支払う',
    payGoogle: 'GOOGLE PAYで支払う',
    manualBank: 'または手動銀行振込',
    accountName: '口座名義',
    bsb: 'BSB',
    accountNumber: '口座番号',

    egJaneDoe: '例: 山田花子',
    egYouthGroup: '例: ユースグループ',
    egPhone: '例: 090-1234-5678',
    egAddress: '例: 東京都渋谷区',
    egOccupation: '例: ソフトウェアエンジニア',
    egHometown: '例: 台湾台北、中国上海',
    egChurchCode: '例: GRACE-2024',
    egEmail: 'your@email.com',
    egNewTag: '新しいタグ（例: 保育所）',
    ourHistory: '教会の歩み',
    secondaryTime: 'お祈り会',
    freeParking: '無料駐車場完備',
    momentsOfGrace: '恵みの瞬間',
    history: '教会の沿革',
    founders: '創設者',
    denomination: '宗派',
    pastors: '牧師',
    groupLeaders: 'グループリーダー',
    ourTeam: '私たちのチーム',
    graceMission: 'すべての魂が恵みによって回復される家を築くこと。',
    foundedYear: '2005年設立',
    independentPentecostal: '独立ペンテコステ派',
    pastorShort: '牧師',
    leaderShort: 'リーダー'
  },
  'ko': {
    dashboard: '대시보드',
    aboutChurch: '교회 소개',
    roster: '명단',
    worshipSongs: '예배 및 찬양',
    prayerWall: '기도 벽',
    members: '회원',
    giving: '헌금',
    support: '지원',
    managerPortal: '관리자 포털',
    managerMode: '관리자 모드',
    staffMode: '스태프 모드',
    memberMode: '회원 모드',
    newEvent: '새 이벤트',

    welcome: '환영합니다',
    signInDesc: '커뮤니티 계정에 로그인하세요.',
    applyDesc: '회원 가입 신청.',
    churchCode: '교회 코드',
    fullName: '성명',
    email: '이메일',
    password: '비밀번호',
    signIn: '로그인',
    submitRequest: '요청 제출',
    moreOptions: '추가 옵션',
    signUpMember: '회원으로 가입하기',
    alreadyAccount: '이미 계정이 있으신가요? 로그인',
    managerLogin: '관리자/스태프 로그인',
    secureEnv: '안전한 환경',
    systemLanguage: '시스템 언어',
    requestSubmitted: '요청 제출됨',
    requestSubmittedDesc: '가입 요청이 전송되었습니다. 관리자나 목사님이 곧 신청서를 검토할 것입니다.',
    backToLogin: '로그인으로 돌아가기',
    // Dashboard
    totalMembers: '총 회원 수',
    activeVolunteers: '활성 자원봉사자',
    weeklyOffering: '주간 헌금',
    newRequests: '새 요청',
    growth: '성장',
    fromLastWeek: '지난주 대비',
    upcomingEvents: '예정된 행사',
    prayerRequests: '기도 요청',
    memberApprovals: '회원 승인',
    reviewSignUps: '가입 요청 검토',
    myTasks: '내 작업',
    personalToDo: '개인 할 일 목록',
    allCaughtUp: '모두 완료!',
    addATask: '작업 추가...',
    addBtn: '추가',
    approveBtn: '승인',
    declineBtn: '거부',
    dailyGoldenVerse: '오늘의 성경 구절',
    pendingApproval: '승인 대기 중',
    viewPlan: '계획 보기',
    servicesDesc: '이번 달 예배, 결혼식 및 캠프',
    thisMonth: '이번 달',
    welcomeBack: '환영합니다',
    pastorDavid: '데이빗 목사님',
    teamMember: '팀원',
    printRoster: '명단 인쇄',
    preparing: '준비 중...',
    recentActivity: '최근 활동',
    loadMore: '더 보기',
    loading: '로딩 중...',
    justNow: '방금',
    minsAgo: '분 전',
    hourAgo: '1시간 전',
    hoursAgo: '시간 전',
    uploadedPpt: '새 PPT 업로드됨',
    declinedRequest: '일정 요청 거부됨',
    submittedPrayer: '새 기도 요청이 제출됨.',
    camping: '캠핑',
    days: '일',
    holyCommunion: '성찬식',
    sundayWorshipService: '주일 예배',
    youthWinterCamp: '청년 겨울 캠프',
    johnMaryWedding: '존과 메리의 결혼식',
    search: '검색...',
    logout: '로그아웃',
    howCanIHelp: '오늘 무엇을 도와드릴까요?',
    askAbout: '교회 직원, 예배 일정 또는 신학적 통찰력에 대해 질문하십시오.',
    checkRoster: '일정 확인',
    memberStats: '회원 통계',
    prayerList: '기도 목록',
    askGrace: 'Grace 도우미에게 질문하기...',
    outOfTown: '"이번 주말에는 도시에 없습니다."',
    sunday: '일',
    friday: '금',
    saturday: '토',

    // New additions
    learnMoreAbout: '우리의 비전, 사명, 가족에 대해 자세히 알아보십시오.',
    editDetails: '세부 정보 편집',
    churchTitle: '그레이스 커뮤니티 교회',
    churchDesc: '우리는 사랑, 은혜, 희망을 나누는 데 전념하는 환영하는 커뮤니티입니다. 우리의 사명은 도시를 섬기고 강력한 신앙의 가정을 세우는 것입니다.',
    serviceTimes: '예배 시간',
    serviceTimesDesc: '일요일 오전 9:00 & 오전 11:00',
    location: '위치',
    locationDesc: '123 Grace Ave, Sydney, NSW 2000',
    photoGallery: '사진 갤러리',
    personalInfo: '개인 정보',
    firstNameProfile: '이름',
    lastNameProfile: '성',
    emailAddress: '이메일 주소',
    phoneNumber: '전화번호',
    dateOfBirth: '생년월일',
    age: '나이',
    address: '주소',
    hometown: '고향/출신',
    preferredLanguage: '선호하는 언어',
    joinedLabel: '가입함',
    statusLabel: '상태',
    activeStatus: '활성',
    saveChanges: '변경 사항 저장',
    serviceRoster: '서비스 명단',
    rosterDesc: '직원 할당을 관리하고 일정 충돌을 식별합니다.',
    monthly: '월간',
    weekly: '주간',
    availableStaff: '근무 가능한 직원',
    dragToAssign: '드래그하여 할당',
    activityLog: '활동 로그',
    assignedToWorship: '예배팀에 할당됨',
    onLeave: '휴가 중',
    mon: '월',
    tue: '화',
    wed: '수',
    thu: '목',
    searchHymns: '찬송가/찬양 검색',
    allSongs: '전체',
    worshipSongsTab: '예배',
    praiseSongs: '찬양',
    communionSongs: '성찬식',
    defaultKey: '기본 키',
    tempo: '템포',
    timeSig: '박자',
    ccli: 'CCLI',
    lyricsAndChords: '가사 및 코드',
    slidesAndMedia: '슬라이드 및 미디어',
    generatePpt: '가사에서 PPT 생성',
    syncToDrive: '드라이브에 동기화',
    prayerWallDesc: '"기도를 항상 힘쓰고..." - 골로새서 4:2',
    sharePrayer: '기도 나누기',
    whatsOnYourHeart: '마음에 무슨 생각이 있습니까?',
    postAnonymously: '익명으로 게시',
    visibility: '공개 범위',
    postPrayer: '기도 게시',
    pray: '기도하기',
    staffOnly: '직원',
    memberNetwork: '회원 네트워크',
    memberNetworkDesc: '관계, 영적 가족 및 직원 세부 정보 보기.',
    searchName: '이름 검색...',
    filterByTag: '태그로 필터링...',
    addMemberBtn: '추가',
    interactiveMapping: '대화형 관계 매핑',
    joinedYear: '가입',
    relationalContext: '관계 상황',
    invitedBy: '초대한 사람',
    spiritualFamily: '영적 가족',
    personalDetails: '개인 세부 정보',
    addNewMember: '새 회원 추가',
    fullNameStar: '전체 이름 *',
    tagsRoles: '태그 / 역할',
    spiritualGroup: '영적 가족 / 그룹',
    invitedByName: '초대한 사람 (이름)',
    phoneLabel: '전화번호',
    dobLabel: '생년월일',
    homeAddress: '자택 주소',
    occupation: '직업',
    cancel: '취소',
    saveMember: '회원 저장',
    matchExisting: '기존 회원 이름 일치',
    customTag: '사용자 지정 태그...',
    giveTithes: '십일조 및 헌금',
    giveDesc: '"하나님은 즐겨 내는 자를 사랑하시느니라." - 고린도후서 9:7',
    customAmount: '$ 사용자 지정 금액',
    payApple: 'APPLE PAY로 결제',
    payGoogle: 'GOOGLE PAY로 결제',
    manualBank: '또는 수동 계좌 이체',
    accountName: '계좌명',
    bsb: 'BSB',
    accountNumber: '계좌 번호',

    egJaneDoe: '예: 홍길동',
    egYouthGroup: '예: 청년부',
    egPhone: '예: 010-1234-5678',
    egAddress: '예: 서울시 강남구',
    egOccupation: '예: 소프트웨어 엔지니어',
    egHometown: '예: 대만 타이베이, 중국 상하이',
    egChurchCode: '예: GRACE-2024',
    egEmail: 'your@email.com',
    egNewTag: '새 태그 (예: 탁아소)',
    ourHistory: '교회 역사 안내',
    secondaryTime: '기도 모임',
    freeParking: '무료 주차 제공',
    momentsOfGrace: '은혜의 순간들',
    history: '교회 역사',
    founders: '설립자',
    denomination: '교단',
    pastors: '목사님',
    groupLeaders: '소그룹 리더',
    ourTeam: '우리 팀',
    graceMission: '모든 영혼이 은혜로 회복되는 가정을 세우는 것.',
    foundedYear: '2005년 설립',
    independentPentecostal: '독립 오순절 교회',
    pastorShort: '목사',
    leaderShort: '리더'
  },
  'th': {
    dashboard: 'แผงควบคุม',
    aboutChurch: 'เกี่ยวกับคริสตจักร',
    roster: 'ตารางเวร',
    worshipSongs: 'นมัสการและเพลง',
    prayerWall: 'กำแพงคำอธิษฐาน',
    members: 'สมาชิก',
    giving: 'การถวาย',
    support: 'สนับสนุน',
    managerPortal: 'พอร์ทัลผู้จัดการ',
    managerMode: 'โหมดผู้จัดการ',
    staffMode: 'โหมดเจ้าหน้าที่',
    memberMode: 'โหมดสมาชิก',
    newEvent: 'กิจกรรมใหม่',

    welcome: 'ยินดีต้อนรับ',
    signInDesc: 'เข้าสู่ระบบบัญชีชุมชนของคุณ',
    applyDesc: 'สมัครสมาชิก',
    churchCode: 'รหัสคริสตจักร',
    fullName: 'ชื่อ-นามสกุล',
    email: 'อีเมล',
    password: 'รหัสผ่าน',
    signIn: 'เข้าสู่ระบบ',
    submitRequest: 'ส่งคำขอ',
    moreOptions: 'ตัวเลือกเพิ่มเติม',
    signUpMember: 'ลงทะเบียนสมัครสมาชิก',
    alreadyAccount: 'มีบัญชีอยู่แล้ว? เข้าสู่ระบบ',
    managerLogin: 'เข้าสู่ระบบผู้จัดการ/เจ้าหน้าที่',
    secureEnv: 'สภาพแวดล้อมที่ปลอดภัย',
    systemLanguage: 'ภาษาของระบบ',
    requestSubmitted: 'ส่งคำขอแล้ว',
    requestSubmittedDesc: 'คำขอเข้าร่วมชุมชนของคุณถูกส่งแล้ว ผู้จัดการหรือศิษยาภิบาลจะตรวจสอบใบสมัครของคุณเร็วๆ นี้',
    backToLogin: 'กลับไปหน้าเข้าสู่ระบบ',

    totalMembers: 'สมาชิกทั้งหมด',
    activeVolunteers: 'อาสาสมัครที่กระตือรือร้น',
    weeklyOffering: 'เงินถวายประจำสัปดาห์',
    newRequests: 'คำขอใหม่',
    growth: 'การเติบโต',
    fromLastWeek: 'จากสัปดาห์ที่แล้ว',
    upcomingEvents: 'กิจกรรมที่กำลังจะมาถึง',
    prayerRequests: 'คำขอคำอธิษฐาน',
    memberApprovals: 'การอนุมัติสมาชิก',
    reviewSignUps: 'ตรวจสอบคำขอลงทะเบียน',
    myTasks: 'งานของฉัน',
    personalToDo: 'รายการสิ่งที่ต้องทำส่วนตัว',
    allCaughtUp: 'เรียบร้อยทุกอย่าง!',
    addATask: 'เพิ่มงาน...',
    addBtn: 'เพิ่ม',
    approveBtn: 'อนุมัติ',
    declineBtn: 'ปฏิเสธ',
    dailyGoldenVerse: 'พระคำประจำวัน',
    pendingApproval: 'รอการอนุมัติ',
    viewPlan: 'ดูแผนการ',
    servicesDesc: 'พิธีการ งานแต่งงาน และแคมป์ประจำเดือน',
    thisMonth: 'เดือนนี้',
    welcomeBack: 'ยินดีต้อนรับกลับมา',
    pastorDavid: 'ศจ.เดวิด',
    teamMember: 'สมาชิกในทีม',
    printRoster: 'พิมพ์ตารางเวร',
    preparing: 'กำลังเตรียมการ...',
    recentActivity: 'กิจกรรมล่าสุด',
    loadMore: 'โหลดเพิ่มเติม',
    loading: 'กำลังโหลด...',
    justNow: 'เมื่อครู่',
    minsAgo: 'นาทีที่แล้ว',
    hourAgo: '1 ชั่วโมงที่แล้ว',
    hoursAgo: 'ชั่วโมงที่แล้ว',
    uploadedPpt: 'อัปโหลด PPT ใหม่สำหรับ',
    declinedRequest: 'ปฏิเสธคำขอจัดตารางในวันที่',
    submittedPrayer: 'ส่งคำขอคำอธิษฐานใหม่',
    approvedMembership: 'อนุมัติการเป็นสมาชิกสำหรับ',
    scheduledAction: 'ตารางเวลา',
    updatedHistory: 'อัปเดตประวัติ',
    addedRelationship: 'เพิ่มความสัมพันธ์',
    followUpVisitors: 'ติดตามผลกับผู้มาเยือนใหม่',
    prepareSermonSlides: 'เตรียมสไลด์เทศนาวันอาทิตย์',
    changeVerse: 'เปลี่ยนข้อพระคัมภีร์',
    editBtn: 'แก้ไข',
    myService: 'การรับใช้ของฉัน',
    teamReadiness: 'ความพร้อมของทีม',
    confirmed: 'ยืนยันแล้ว',
    approvals: 'การอนุมัติ',
    itemsWaiting: 'รายการที่รอ',
    newMembers: 'สมาชิกใหม่',
    viewAll: 'ดูทั้งหมด',
    coreValues: 'ค่านิยมหลัก',
    love: 'ความรัก',
    serve: 'การรับใช้',
    disciple: 'การสร้างสาวก',
    navigation: 'นำทาง',
    viewMap: 'ดูแผนที่',
    founder: 'ผู้ก่อตั้ง',
    denomination: 'คณะนิกาย',
    highlightEvent: 'กิจกรรมเด่น',
    comingNext: 'รายการถัดไป',
    upcomingRole: 'บทบาทที่กำลังจะมาถึง',
    addToCalendar: 'เพิ่มลงในปฏิทิน',
    liveUpdates: 'อัปเดตสด',
    eventTitle: 'หัวข้อกิจกรรม',
    type: 'ประเภท',
    date: 'วันที่',
    reminder: 'การแจ้งเตือน',
    createEvent: 'สร้างกิจกรรม',
    sundayWorship: 'การนมัสการวันอาทิตย์',
    goodFriday: 'วันศุกร์ประเสริฐ',
    anniversaryCelebration: 'ฉลองครบรอบ',
    verse1_quote: 'ความเชื่อคือความแน่ใจในสิ่งที่หวังไว้',
    verse2_quote: 'พระคุณอันล้นเหลือ',
    verse3_quote: 'ความรักไม่มีวันสูญสิ้น',
    verse4_quote: 'ดำเนินด้วยความเชื่อ',
    verse5_quote: 'เรามอบสันติสุขไว้ให้แก่ท่าน',
    verse6_quote: 'จงสัตย์ซื่อในสิ่งเล็กน้อย',
    mainSanctuary: 'ห้องประชุมใหญ่',
    worshipLeader: 'ผู้นำนมัสการ',
    camping: 'แคมป์ไฟ',
    days: 'วัน',
    holyCommunion: 'พิธีมหาสนิท',
    sundayWorshipService: 'พิธีนมัสการวันอาทิตย์',
    youthWinterCamp: 'แคมป์วัยรุ่นฤดูหนาว',
    johnMaryWedding: 'งานแต่งงานของจอห์นและแมรี่',
    meeting: 'การประชุม',
    search: 'ค้นหา...',
    logout: 'ออกจากระบบ',
    howCanIHelp: 'ฉันจะช่วยอะไรคุณได้บ้างในวันนี้',
    askAbout: 'ถามเกี่ยวกับบุคลากรของคริสตจักร ตารางเวลา หรือความรู้ทางเทววิทยา',
    checkRoster: 'ตรวจสอบตารางงาน',
    memberStats: 'สถิติสมาชิก',
    prayerList: 'รายการสวดมนต์',
    askGrace: 'ถามผู้ช่วยของ Grace...',
    outOfTown: '"ไปต่างจังหวัดสุดสัปดาห์นี้"',
    sunday: 'อา.',
    friday: 'ศ.',
    saturday: 'ส.',

    learnMoreAbout: 'เรียนรู้เพิ่มเติมเกี่ยวกับนิมิต พันธกิจ และครอบครัวของเรา',
    editDetails: 'แก้ไขรายละเอียด',
    churchTitle: 'คริสตจักรชุมชนพระคุณ',
    churchDesc: 'เราเป็นชุมชนที่ยินดีต้อนรับผู้อื่น อุทิศตนเพื่อแบ่งปันความรัก พระคุณ และความหวัง พันธกิจของเราคือการรับใช้คนในเมืองและสร้างครอบครัวแห่งความเชื่อที่เข้มแข็ง',
    serviceTimes: 'เวลาพิธีการ',
    serviceTimesDesc: 'วันอาทิตย์ เวลา 09:00 น. และ 11:00 น.',
    location: 'สถานที่',
    locationDesc: '123 Grace Ave, Sydney, NSW 2000',
    photoGallery: 'แกลเลอรีรูปภาพ',
    personalInfo: 'ข้อมูลส่วนตัว',
    firstNameProfile: 'ชื่อ',
    lastNameProfile: 'นามสกุล',
    emailAddress: 'ที่อยู่อีเมล',
    phoneNumber: 'หมายเลขโทรศัพท์',
    dateOfBirth: 'วันเกิด',
    age: 'อายุ',
    address: 'ที่อยู่',
    hometown: 'บ้านเกิด / ภูมิลำเนา',
    preferredLanguage: 'ภาษาที่ต้องการ',
    joinedLabel: 'เข้าร่วมเมื่อ',
    statusLabel: 'สถานะ',
    activeStatus: 'ใช้งานอยู่',
    saveChanges: 'บันทึกการเปลี่ยนแปลง',
    serviceRoster: 'ตารางการรับใช้',
    rosterDesc: 'จัดการการมอบหมายเจ้าหน้าที่และระบุข้อขัดแย้งของตารางเวลา',
    monthly: 'รายเดือน',
    weekly: 'รายสัปดาห์',
    availableStaff: 'เจ้าหน้าที่ที่ว่าง',
    dragToAssign: 'ลากเพื่อมอบหมาย',
    activityLog: 'บันทึกกิจกรรม',
    assignedToWorship: 'ได้รับมอบหมายให้นมัสการ',
    onLeave: 'ลาพัก',
    mon: 'จ.',
    tue: 'อ.',
    wed: 'พ.',
    thu: 'พฤ.',
    searchHymns: 'ค้นหาเพลงสวด / เพลงสรรเสริญ',
    allSongs: 'ทั้งหมด',
    worshipSongsTab: 'นมัสการ',
    praiseSongs: 'สรรเสริญ',
    communionSongs: 'มหาสนิท',
    defaultKey: 'คีย์เริ่มต้น',
    tempo: 'ความเร็ว',
    timeSig: 'จังหวะ',
    ccli: 'CCLI',
    lyricsAndChords: 'เนื้อเพลงและคอร์ด',
    slidesAndMedia: 'สไลด์และสื่อ',
    generatePpt: 'สร้าง PPT จากเนื้อเพลง',
    syncToDrive: 'ซิงค์กับไดรฟ์',
    prayerWallDesc: '"จงอุทิศตัวในการอธิษฐาน..." - โคโลสี 4:2',
    sharePrayer: 'แบ่งปันคำอธิษฐาน',
    whatsOnYourHeart: 'มีอะไรอยู่ในใจของคุณ?',
    postAnonymously: 'โพสต์โดยไม่ระบุชื่อ',
    visibility: 'การมองเห็น',
    postPrayer: 'โพสต์คำอธิษฐาน',
    pray: 'อธิษฐาน',
    staffOnly: 'เจ้าหน้าที่',
    memberNetwork: 'เครือข่ายสมาชิก',
    memberNetworkDesc: 'ดูความสัมพันธ์ ครอบครัวฝ่ายวิญญาณ และรายละเอียดเจ้าหน้าที่',
    searchName: 'ค้นหาชื่อ...',
    filterByTag: 'กรองตามแท็ก...',
    addMemberBtn: 'เพิ่ม',
    interactiveMapping: 'การแผนผังความสัมพันธ์แบบโต้ตอบ',
    joinedYear: 'เข้าร่วมปี',
    relationalContext: 'บริบททางความสัมพันธ์',
    invitedBy: 'ได้รับคำเชิญโดย',
    spiritualFamily: 'ครอบครัวฝ่ายวิญญาณ',
    personalDetails: 'รายละเอียดส่วนตัว',
    addNewMember: 'เพิ่มสมาชิกใหม่',
    fullNameStar: 'ชื่อ-นามสกุล *',
    tagsRoles: 'แท็ก / บทบาท',
    spiritualGroup: 'ครอบครัว / กลุ่มฝ่ายวิญญาณ',
    invitedByName: 'ชื่อผู้เชิญ',
    phoneLabel: 'หมายเลขโทรศัพท์',
    dobLabel: 'วันเกิด',
    homeAddress: 'ที่อยู่บ้าน',
    occupation: 'อาชีพ',
    cancel: 'ยกเลิก',
    saveMember: 'บันทึกสมาชิก',
    matchExisting: 'ตรงกับชื่อสมาชิกที่มีอยู่',
    customTag: 'แท็กที่กำหนดเอง...',
    giveTithes: 'ถวายสิบลดและเงินถวาย',
    giveDesc: '"พระเจ้าทรงรักคนที่ให้ด้วยใจยินดี" - 2 โครินธ์ 9:7',
    customAmount: '$ ระบุจำนวน',
    payApple: 'ชำระด้วย APPLE PAY',
    payGoogle: 'ชำระด้วย GOOGLE PAY',
    manualBank: 'หรือโอนผ่านธนาคารโดยตรง',
    accountName: 'ชื่อบัญชี',
    bsb: 'BSB',
    accountNumber: 'เลขที่บัญชี',

    egJaneDoe: 'เช่น เจน โด',
    egYouthGroup: 'เช่น กลุ่มวัยรุ่น',
    egPhone: 'เช่น 081-123-4567',
    egAddress: 'เช่น 123 ถนนสุขุมวิท กรุงเทพฯ',
    egOccupation: 'เช่น วิศวกรซอฟต์แวร์',
    egHometown: 'เช่น กรุงเทพฯ, เชียงใหม่ / ไทเป, ไต้หวัน',
    egChurchCode: 'เช่น GRACE-2024',
    egEmail: 'your@email.com',
    egNewTag: 'แท็กใหม่ (เช่น เนอสเซอรี่)',
    history: 'ประวัติของเรา',
    founders: 'ผู้ก่อตั้ง',
    pastors: 'ศิษยาภิบาล',
    groupLeaders: 'ผู้นำกลุ่ม',
    ourTeam: 'ทีมงานของเรา',
    graceMission: 'เพื่อสร้างบ้านที่ทุกดวงวิญญาณได้รับการฟื้นฟูดั่งพระคุณ',
    foundedYear: 'ก่อตั้งขึ้นในปี 2005',
    independentPentecostal: 'เพนเทคอสเปนอิสระ',
    pastorShort: 'ศจ.',
    leaderShort: 'ลีดเดอร์'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>('en');

  useEffect(() => {
    const saved = localStorage.getItem('app-language');
    if (saved && saved !== 'system') {
      setLanguageState(saved as Language);
    } else {
      const browserLang = navigator.language.toLowerCase();
      if (browserLang.startsWith('zh-cn')) setLanguageState('zh-CN');
      else if (browserLang.startsWith('zh-tw') || browserLang.startsWith('zh-hk')) setLanguageState('zh-TW');
      else if (browserLang.startsWith('ja')) setLanguageState('ja');
      else if (browserLang.startsWith('ko')) setLanguageState('ko');
      else if (browserLang.startsWith('th')) setLanguageState('th');
      else setLanguageState('en');
    }
  }, []);

  const setLanguage = (lang: Language | 'system') => {
    localStorage.setItem('app-language', lang);
    if (lang === 'system') {
      const browserLang = navigator.language.toLowerCase();
      if (browserLang.startsWith('zh-cn')) setLanguageState('zh-CN');
      else if (browserLang.startsWith('zh-tw') || browserLang.startsWith('zh-hk')) setLanguageState('zh-TW');
      else if (browserLang.startsWith('ja')) setLanguageState('ja');
      else if (browserLang.startsWith('ko')) setLanguageState('ko');
      else if (browserLang.startsWith('th')) setLanguageState('th');
      else setLanguageState('en');
    } else {
      setLanguageState(lang);
    }
  };

  const t = (key: string): string => {
    if (!translations[language]) return (translations['en'] as any)[key] || key;
    return (translations[language] as any)[key] || (translations['en'] as any)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
